baseURL = 'https://lionel-fillatre.github.io/'
languageCode = 'en-us'
title = "Lionel Fillatre's Personal Website"
metaDataFormat = "toml"

theme = "ananke"

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
  background_color_class = "bg-navy" # bg-dark-blue


[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

  [[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 4

  [[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 5
  
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 6


