baseURL = 'https://lionel-fillatre.github.io/'
languageCode = 'en-us'
title = "Lionel Fillatre's Personal Website"
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
theme = 'ananke'
